// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTCNAb-HZJ1FiBxs0JBSIpnQapKuezwnc',
    appId: '1:102010090087:web:aa3ef497521ad951b69ac2',
    messagingSenderId: '102010090087',
    projectId: 'papb-b0e85',
    authDomain: 'papb-b0e85.firebaseapp.com',
    storageBucket: 'papb-b0e85.firebasestorage.app',
    measurementId: 'G-0SEMHM8SQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQA9RCyOTpL7vDJJET6mZ4AAgtBDFqus',
    appId: '1:102010090087:android:d2241edadc7d4111b69ac2',
    messagingSenderId: '102010090087',
    projectId: 'papb-b0e85',
    storageBucket: 'papb-b0e85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJa4T5Qu6hz3myo11B6clqIwp_SHUkkmE',
    appId: '1:102010090087:ios:e05107a80c496507b69ac2',
    messagingSenderId: '102010090087',
    projectId: 'papb-b0e85',
    storageBucket: 'papb-b0e85.firebasestorage.app',
    iosBundleId: 'com.example.papb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJa4T5Qu6hz3myo11B6clqIwp_SHUkkmE',
    appId: '1:102010090087:ios:e05107a80c496507b69ac2',
    messagingSenderId: '102010090087',
    projectId: 'papb-b0e85',
    storageBucket: 'papb-b0e85.firebasestorage.app',
    iosBundleId: 'com.example.papb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTCNAb-HZJ1FiBxs0JBSIpnQapKuezwnc',
    appId: '1:102010090087:web:1a5274271aa02b0ab69ac2',
    messagingSenderId: '102010090087',
    projectId: 'papb-b0e85',
    authDomain: 'papb-b0e85.firebaseapp.com',
    storageBucket: 'papb-b0e85.firebasestorage.app',
    measurementId: 'G-NYG4Z1GFJD',
  );
}
